/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notquitelisp;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class InstructionsTest {

    @Test
    void openBracketMovesUp1Floor() {
        assertEquals(1, Instructions.followToFloor("("));
    }

    @Test
    void closeBracketMovesDown1Floor() {
        assertEquals(-1, Instructions.followToFloor(")"));
    }

    @Test
    void upx3downx2_is1() {
        assertEquals(1, Instructions.followToFloor("((())"));
    }

    @Test
    void upx3downx4_is7stepsToBasement() {
        assertEquals(7, Instructions.instructionsToBasement("((())))"));
    }
}
